spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs
    username: root
    password: dan123

  jpa:
    show-sql: true

jwt:
  secret: mMZJH4r9K2fJ0XK6uXJbK3KJpXc7JtJxqN4v7FJQkQw=

server:
  port: 5000
