{
  "status": "OK",
  "request_id": "47525812-c371-40da-9271-f31d55a9233b",
  "parameters": {
    "category_id": "281407",
    "country": "US",
    "sort_by": "RELEVANCE",
    "page": 1,
    "is_prime": false,
    "language": "en_US"
  },
  "data": {
    "total_products": 74146,
    "country": "US",
    "domain": "www.amazon.com",
    "products": [
      {
        "asin": "B0DCH8VDXF",
        "product_title": "Apple EarPods Headphones with USB-C Plug, Wired Ear Buds with Built-in Remote to Control Music, Phone Calls, and Volume",
        "product_price": "$17.99",
        "product_original_price": "$19.00",
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 25439,
        "product_url": "https://www.amazon.com/dp/B0DCH8VDXF",
        "product_photo": "https://m.media-amazon.com/images/I/513OSdW4elL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 4,
        "product_minimum_offer_price": "$16.09",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0FQFB8FMG",
        "product_title": "Apple AirPods Pro 3 Wireless Earbuds, Active Noise Cancellation, Live Translation, Heart Rate Sensing,Hearing Aid Feature,Bluetooth Headphones,Spatial Audio, High-Fidelity Sound, USB-C Charging, White",
        "product_price": "$229.99",
        "product_original_price": "$249.00",
        "currency": "USD",
        "product_star_rating": "4.4",
        "product_num_ratings": 5413,
        "product_url": "https://www.amazon.com/dp/B0FQFB8FMG",
        "product_photo": "https://m.media-amazon.com/images/I/61solmQSSlL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 7,
        "product_minimum_offer_price": "$189.40",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11Or fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0D54JZTHY",
        "product_title": "Apple AirTag (1st Generation) - 4 Pack. Keep Track of and find Your Keys, Wallet, Luggage, Backpack, and More. Simple one-tap Set up with iPhone or iPad, Bluetooth",
        "product_price": "$64.00",
        "product_original_price": "$99.00",
        "currency": "USD",
        "product_star_rating": "4.8",
        "product_num_ratings": 40790,
        "product_url": "https://www.amazon.com/dp/B0D54JZTHY",
        "product_photo": "https://m.media-amazon.com/images/I/61bMNCeAUAL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 5,
        "product_minimum_offer_price": "$60.80",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11Or fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0CWXNS552",
        "product_title": "Apple AirTag (1st Generation). Keep Track of and find Your Keys, Wallet, Luggage, Backpack, and More. Simple one-tap Set up with iPhone or iPad, Bluetooth",
        "product_price": "$17.00",
        "product_original_price": "$29.00",
        "currency": "USD",
        "product_star_rating": "4.7",
        "product_num_ratings": 52665,
        "product_url": "https://www.amazon.com/dp/B0CWXNS552",
        "product_photo": "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$17.00",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Feb 13 - 20 on $35 of items shipped by AmazonOr fastest delivery Feb 12 - 18",
        "has_variations": false
      },
      {
        "asin": "B0DGJ7HYG1",
        "product_title": "Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones, with Active Noise Cancellation, Adaptive, Transparency Mode, Personalized Spatial Audio, USB-C Charging Case, Wireless Charging, H2 Chip",
        "product_price": "$139.99",
        "product_original_price": "$179.00",
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 40424,
        "product_url": "https://www.amazon.com/dp/B0DGJ7HYG1",
        "product_photo": "https://m.media-amazon.com/images/I/61iBtxCUabL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 7,
        "product_minimum_offer_price": "$117.62",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11Or fastest delivery Mon, Feb 9",
        "has_variations": false
      },
      {
        "asin": "B0B283QP2N",
        "product_title": "FEEL2NICE iPhone Charger Fast Charging 2 Pack Type C Wall Charger Block with 2 Pack [6FT&amp;10FT] Long USB C to Lightning Cable for iPhone 14/13/12/12 Pro Max/11/Xs Max/XR/X,AirPods Pro",
        "product_price": "$7.99",
        "unit_price": "$4.00",
        "unit_count": 2,
        "product_original_price": "$13.99",
        "currency": "USD",
        "product_star_rating": "4.4",
        "product_num_ratings": 40550,
        "product_url": "https://www.amazon.com/dp/B0B283QP2N",
        "product_photo": "https://m.media-amazon.com/images/I/61rGWwyFDjL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$7.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false,
        "product_badge": "Limited time deal"
      },
      {
        "asin": "B08TJRVWV1",
        "product_title": "Amazon Basics Micro SDXC Memory Card with Full Size Adapter, A2, U3, Read Speed up to 100 MB/s, 128 GB, Black",
        "product_price": null,
        "product_original_price": null,
        "currency": null,
        "product_star_rating": "4.7",
        "product_num_ratings": 142013,
        "product_url": "https://www.amazon.com/dp/B08TJRVWV1",
        "product_photo": "https://m.media-amazon.com/images/I/81FMYuiSaEL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": null,
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "Currently unavailable.",
        "has_variations": false
      },
      {
        "asin": "B09PDLBFKY",
        "product_title": "6 Ft Surge Protector Power Strip - 8 Widely Outlets with 4 USB Ports, 3 Side Outlet Extender with 6 Feet Extension Cord, Flat Plug, Wall Mount, Desk USB Charging Station, ETL,White ClimatePartner certified",
        "product_price": "$9.99",
        "product_original_price": "$12.48",
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 46205,
        "product_url": "https://www.amazon.com/dp/B09PDLBFKY",
        "product_photo": "https://m.media-amazon.com/images/I/61NGPmmMAIL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B088NRLMPV",
        "product_title": "Anker USB C to USB C Cable, Type-C 60W Fast Charging Cable (6 FT, 2Pack) for iPhone 17 Series, iPad mini 6 and More (Black) ClimatePartner certified",
        "product_price": "$9.99",
        "unit_price": "$5.00",
        "unit_count": 2,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.7",
        "product_num_ratings": 76129,
        "product_url": "https://www.amazon.com/dp/B088NRLMPV",
        "product_photo": "https://m.media-amazon.com/images/I/71IE9dLBduL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0CB1FW5FC",
        "product_title": "INIU Portable Charger, Ultra Slim 45W Fast Charging with Attached USB C Cable, Flight-Safe 10000mAh PD Power Bank Battery Pack, Travel Essential Phone Powerbank for iPhone 17 16 Samsung S25 Google etc ClimatePartner certified",
        "product_price": "$20.99",
        "product_original_price": "$23.99",
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 72635,
        "product_url": "https://www.amazon.com/dp/B0CB1FW5FC",
        "product_photo": "https://m.media-amazon.com/images/I/71gH0eRJcFL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 14,
        "product_minimum_offer_price": "$18.42",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Mon, Feb 9",
        "has_variations": true
      },
      {
        "asin": "B09KR8P3L5",
        "product_title": "iPhone 17 16 15 Charger Fast Charging Type C Chargers USB C Charger Block iPhone 17 16 15 Air Pro Max Chargers with 6FT Cable for iPhone 17/17 Plus/17 Pro Max/16/16 Plus/16 Pro Max/15 Pro Max/iPad Pro",
        "product_price": "$8.90",
        "unit_price": "$4.45",
        "unit_count": 2,
        "product_original_price": "$16.90",
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 31078,
        "product_url": "https://www.amazon.com/dp/B09KR8P3L5",
        "product_photo": "https://m.media-amazon.com/images/I/61lzntb+BnL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$8.90",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Mon, Feb 9",
        "has_variations": false,
        "product_badge": "Limited time deal"
      },
      {
        "asin": "B0FDQK69GQ",
        "product_title": "Ailun 3 Pack Screen Protector for iPhone 17 Pro Max [6.9 inch] with Installation Frame, Tempered Glass, Sensor Protection, Dynamic Island Compatible, Case Friendly Global Recycled Standard",
        "product_price": "$6.98",
        "unit_price": "$2.33",
        "unit_count": 3,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 1112649,
        "product_url": "https://www.amazon.com/dp/B0FDQK69GQ",
        "product_photo": "https://m.media-amazon.com/images/I/71XuFtl2aBL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$6.98",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B092J8LPWR",
        "product_title": "Surge Protector Power Strip - HANYCONY 8 Outlets 4 USB (2 USB C) Charging Ports, Multi Plug Outlet Extender, 5Ft Braided Extension Cord, Flat Plug Wall Mount Desk Charging Station for Home Office ETL",
        "product_price": "$11.99",
        "product_original_price": "$12.99",
        "currency": "USD",
        "product_star_rating": "4.8",
        "product_num_ratings": 64117,
        "product_url": "https://www.amazon.com/dp/B092J8LPWR",
        "product_photo": "https://m.media-amazon.com/images/I/61q9hmplGFL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$11.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0B2WLSY9D",
        "product_title": "[4 Pack] USB C Charger Block Fast Charging Multiport Adpater [PD 20W USB-C &amp; QC 3.0 USB-A Port] for iPhone 17/16/15/14/13/12/11/X/8, iPad, Galaxy, Google &amp; More",
        "product_price": "$9.98",
        "unit_price": "$2.50",
        "unit_count": 4,
        "product_original_price": "$11.99",
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 9093,
        "product_url": "https://www.amazon.com/dp/B0B2WLSY9D",
        "product_photo": "https://m.media-amazon.com/images/I/51eAnSUfXSL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.98",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false,
        "product_badge": "Limited time deal"
      },
      {
        "asin": "B08R6S1M1K",
        "product_title": "Wall Charger, Surge Protector, QINLIANF 5 Outlet Extender with 4 USB Charging Ports (4.8A Total) 3-Sided 1680J Power Strip Multi Plug Adapter Spaced for Home Travel Office (3U1C) ClimatePartner certified",
        "product_price": "$9.99",
        "product_original_price": "$12.96",
        "currency": "USD",
        "product_star_rating": "4.7",
        "product_num_ratings": 109530,
        "product_url": "https://www.amazon.com/dp/B08R6S1M1K",
        "product_photo": "https://m.media-amazon.com/images/I/61Hh-YlfJOL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B08412PTS8",
        "product_title": "HP 67XL Black High-Yield Ink Cartridge | Works with DeskJet 1255, 2700, 4100, Envy 6000, 6400 Series | Eligible for Instant Ink | 3YM57AN | Packaging May Vary ECOLOGO",
        "product_price": "$35.89",
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 105799,
        "product_url": "https://www.amazon.com/dp/B08412PTS8",
        "product_photo": "https://m.media-amazon.com/images/I/71HHyV8DV-L._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$35.89",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "50K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11Or fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0DJFW7PNM",
        "product_title": "Apple 20W USB-C Compact Power Adapter: Fast and Convenient Charging, Type C Wall Charger",
        "product_price": "$14.99",
        "product_original_price": "$19.00",
        "currency": "USD",
        "product_star_rating": "4.8",
        "product_num_ratings": 9543,
        "product_url": "https://www.amazon.com/dp/B0DJFW7PNM",
        "product_photo": "https://m.media-amazon.com/images/I/31EQge6IQQL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 2,
        "product_minimum_offer_price": "$13.45",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0DN1S1YLV",
        "product_title": "ANDERY Car Phone Holder for Magsafe [78+LBS Strongest Suction &amp; 2400gf Magnetic] 360° Adjustable Car Phone Mount, Phone Holders for Your Car for iPhone 17-12, Valentine&#x27;s Day Gifts for Him Her Global Recycled Standard",
        "product_price": "$25.61",
        "product_original_price": "$42.59",
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 16917,
        "product_url": "https://www.amazon.com/dp/B0DN1S1YLV",
        "product_photo": "https://m.media-amazon.com/images/I/716yn62ZrkL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$25.61",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": null,
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Sun, Feb 8Arrives before Valentine's Day",
        "has_variations": false,
        "product_badge": "Limited time deal"
      },
      {
        "asin": "B0FDQG97BP",
        "product_title": "Ailun 3 Pack Screen Protector for iPhone 17 Pro [6.3 inch] + 3 Pack Camera Lens Protector with Installation Frame,Sensor Protection,Dynamic Island Compatible,Case Friendly Tempered Glass Film Global Recycled Standard",
        "product_price": "$9.88",
        "unit_price": "$3.29",
        "unit_count": 3,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.5",
        "product_num_ratings": 409211,
        "product_url": "https://www.amazon.com/dp/B0FDQG97BP",
        "product_photo": "https://m.media-amazon.com/images/I/71ZyAPjoBhL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.88",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B079KL4C91",
        "product_title": "Amazon Basics Clear Thermal Laminating Plastic Paper Laminator Sheets, 9 x 11.5-Inch, 200-Pack, 2.8mil",
        "product_price": "$17.24",
        "unit_price": "$0.09",
        "unit_count": 192,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.8",
        "product_num_ratings": 92004,
        "product_url": "https://www.amazon.com/dp/B079KL4C91",
        "product_photo": "https://m.media-amazon.com/images/I/61cefAp7H5L._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 2,
        "product_minimum_offer_price": "$15.06",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "50K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0C69HB8PM",
        "product_title": "iPhone 17 16 15 Charger Fast Charging,2Pack 20W Apple iPad USB C Wall Chrager Block with 6FT USB C to C Cable for iPhone 17/Pro/Pro Max/17 Air/ 16/16 Pro/16 Pro Max/15/Plus/Pro/Pro Max (White)",
        "product_price": "$9.99",
        "product_original_price": "$12.99",
        "currency": "USD",
        "product_star_rating": "4.7",
        "product_num_ratings": 8234,
        "product_url": "https://www.amazon.com/dp/B0C69HB8PM",
        "product_photo": "https://m.media-amazon.com/images/I/71H6iiwZBbL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$9.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0BGSDTZVF",
        "product_title": "iPhone Charger 3 Pack 10 ft Apple MFi Certified Lightning Nylon Braided Cable Fast Charging Cord Compatible with iPhone 13 12 11 Pro Max XR XS X 8 7 6 Plus SE iPad and More ClimatePartner certified",
        "product_price": "$7.99",
        "unit_price": "$2.66",
        "unit_count": 3,
        "product_original_price": "$9.99",
        "currency": "USD",
        "product_star_rating": "4.4",
        "product_num_ratings": 24703,
        "product_url": "https://www.amazon.com/dp/B0BGSDTZVF",
        "product_photo": "https://m.media-amazon.com/images/I/71PxgcoTvYL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$7.99",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B08412HXK9",
        "product_title": "HP 67 Black/Tri-Color Ink Cartridges (2-Pack) | Works with DeskJet 1255, 2700, 4100, Envy 6000, 6400 | Instant Ink Eligible | 3YP29AN | Packaging May Vary",
        "product_price": "$43.89",
        "unit_price": "$21.95",
        "unit_count": 2,
        "product_original_price": null,
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 61716,
        "product_url": "https://www.amazon.com/dp/B08412HXK9",
        "product_photo": "https://m.media-amazon.com/images/I/71RZodfB3qL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$43.89",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "40K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11Or fastest delivery Tomorrow, Feb 7",
        "has_variations": false
      },
      {
        "asin": "B0DC6GXZSV",
        "product_title": "Surge Protector Power Strip - CHCORE 5Ft Braided Extension Cord with 8 Outlets with 4 USB (2 USB C) Charging Ports, Flat Plug Multi Plug Outlet Extender Charging Station for Home Office, ETL, White ClimatePartner certified",
        "product_price": "$8.96",
        "product_original_price": "$14.98",
        "currency": "USD",
        "product_star_rating": "4.6",
        "product_num_ratings": 6868,
        "product_url": "https://www.amazon.com/dp/B0DC6GXZSV",
        "product_photo": "https://m.media-amazon.com/images/I/61MdVuHxxdL._AC_UL960_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "$8.96",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": true,
        "sales_volume": "10K+ bought in past month",
        "delivery": "FREE delivery Wed, Feb 11 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Feb 7",
        "has_variations": false,
        "product_badge": "Limited time deal"
      }
    ]
  }
}